### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ghost** [fellchase/4chan-media-downloader#1]
Hello when i am trying to download something it give me this error -> http://imgur.com/a/7LZnF . This start happening the last 2-3 days before that i could use it fine

**Comment by fellchase** [comment]
Hi, I'm having the same bug I don't have much time nowadays but definitely going to fix it ASAP 
Unfortunately I haven't found where the problem lies...

**Comment by fellchase** [comment]
I'll fix everything and make everything again, also make sure it works on Linux 
Please come back to see changes at end of March or in April I'll complete this by then...
Thanks for reporting the error ;)

**Comment by ghost** [comment]
No problem i well come back to check the compile version. Thanks for the reply.

**Comment by fellchase** [comment]
Yup almost all over bro as I told April is about to end and new script is working flawlessly here... I have not encountered that error again. I have written the script from scratch again, as I don't want script to be buggy this time so I've included a lot of comments and examples in code, so others can also change it and even debug the error on their own in some cases. 
I have removed the stupid download single video/file feature because one can use browser or wget(in Linux) 
I have also removed requests and now new script will use urllib module instead. Code is much more clean this time, I have tweaked some things to make it work on HTTP  because there are some problems to connect using HTTPS in Windows. Script now also supports Linux.... 
I'm finding and fixing bugs in script most of things are done by now, just exception handling and some problems with unicode characters have risen lately. 
Are you still receiving same error? 
Maybe something was wrong with 4chan networks or something because when you reported error I also faced the same error few days after, I didn't modify the script so there's no reason for error to occur from my/your side, maybe they had some network upgrades or something on that day
Here's a preview of new script 
![screenshot_2017-04-21_18-11-23](https://cloud.githubusercontent.com/assets/11918572/25342888/03a8d4c4-292b-11e7-98e1-261ce47452db.png)

I'm actively working on script, It'll be out within a few days or a week :) 
Thanks for showing interest in it

**Comment by fellchase** [comment]
Maybe something was wrong with 4chan networks or something because when you reported error I also faced the same error few days after, I didn't modify the script so there's no reason for error to occur from my/your side, maybe they had some network upgrades or something on that day

**Comment by ghost** [comment]
Hey. It didn't give me the error this time maybe it was some upgrade from the 4chan side us you told, i didn't thought that you were going to make the script from the scratch i thought that you were going to change a little the script and make it work again but thanks for make the v2 of the program it is nice to have a program that i can run on windows, and about the interest i have about the script is that this script is the only one that works for windows i haven't find a script that is good and easy and friendly for the user to work with it. But again thanks for make the script  again from the scratch. And i am looking forward for your new release.

**Comment by fellchase** [comment]
Cool after I update the file tell me how it is Its now 500 lines because of comments and all
I have no formal education in coding so thinking how to make my code easier to understand.
I was going to make v2 anyway because as you can see the old code is bad, now you can use both scripts if one doesn't work use another haha
BTW from where you got link to this repo my github is not quite popular so I'd like to know ....

**Comment by ghost** [comment]
I just looked around to find a  script that can download all the images/videos from a thread on 4chan, i was just looking to github and i found yours. It was the only one that worked on windows and another one that wasn't as good as yours.  And if i remember correctly i was looking and for a linux script.

Sorry but i have no education in coding ether i am going to start the university on september :) i just find the scripts for now. But i hope i can make one script/program in the future.

Edit: How did you learn coding. Were did you start. What was your first programming languages you learn. I would like to start read some books/pdfs before i start going to university just to have the basics.

**Comment by fellchase** [comment]
Thanks :) you can improve this script in future ;) 
My first language was JS I didn't understood it much I also wanted to learn other scripting languages that's why I turned to Python, I learned Most of python on Youtube ;) It's quite easy to understand. And I did such projects which taught me a lot you can do similar project on other image bulletin boards I was initially going to make it for many image bulletin boards not just 4chan but It was too complex for that time, Now I'm learning more python.
If you want to learn basics of any language you can watch Youtube then you've to do your own projects which will teach a lot. You can read my code if you want I've commented almost every line to make it easy to understand for anyone who has basic to moderate knowledge of python
BTW How's the new script running report any bugs if you found ;)
